[package]
name = "the_vault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = "1.5.3"
cosmwasm-std = "1.5.3"
cw-storage-plus = "1.2.0"
schemars = "0.8.16"
serde = { version = "1.0.196", features = ["derive"] }
thiserror = "1.0.56"
